server {
    listen 80;
    server_name localhost;
    root /usr/share/nginx/html;
    index index.html;

    location / {
        add_header Set-Cookie "flag=RUNISEC{c00ki3_m0nst3r_str1k3s}" always;
        try_files $uri $uri/ =404;
    }
}
